openapi: 3.0.1
info:
  description: Simple API to return greeting messages.
  title: Greeting API
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /greet:
    get:
      parameters:
      - description: Name to greet
        explode: true
        in: query
        name: name
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GreetingResponse"
          description: Successful greeting
      summary: Get greeting message
      x-accepts:
      - application/json
components:
  schemas:
    GreetingResponse:
      example:
        message: "Hello, Shubham!"
      properties:
        message:
          example: "Hello, Shubham!"
          type: string
      type: object
